config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :abouts
  resources :industries
  resources :training_categories
  resources :carousels
  resources :trainings
  resources :offices
  resources :sold_products
  resources :banks
  resources :deliveries
  resources :destinations
  resources :stocks
  resources :extras
  resources :clients
  resources :contacts
  devise_for :users


  root 'site#index'

  resources :products
  resources :product_variants
  resources :manufacturers
  resources :providers
  resources :subcategories
  resources :categories
  resources :measures
  resources :orders
  resources :carts
  resources :password_resets
  resources :users

get 'password_resets/new'
post '/total' => 'orders#calculateTotal'
get '/pay/:id' => 'orders#pay'

#Admin Routes
get '/productos' => 'products#list'
get '/productos/:product_id/variantes' => 'product_variants#list'
get '/productos/:product_id/product_variants/new' => 'product_variants#new'
get '/productos/:product_id/product_variants/:id/edit' => 'product_variants#edit'
get '/unidades' => 'measures#list'
get '/fabricantes' =>'manufacturers#list'
get '/proveedores' =>'providers#list'
get '/categorias' => 'categories#list'
get '/subcategorias' => 'subcategories#list'
get '/contacto' => 'contacts#list'
get '/extra' => 'extras#list'
get '/almacen' => 'stocks#list'
get '/usuarios' => 'users#list'
get '/usuarios/:id/habilitar' => 'users#enable'
post '/users/do_enable' => 'users#do_enable'
delete '/usuarios/:id' => 'users#destroy'
get '/usuarios/:id/bloquear' => 'users#bloq'
get '/usuarios/:id/desbloquear' => 'users#desbloq'
get '/transportes' => 'transports#list'
get '/destinos' => 'destinations#list'
get '/envios' => 'deliveries#list'
get '/ordenes' => 'orders#list'
get '/ordenes/:id/editar' => 'orders#change'
post '/orders/do_change' => 'orders#do_change'
get '/reportes/productos_vendidos' => 'carts#reports'
get '/reportes/productos_stock' => 'stocks#reports'
get '/reportes/productos_vendidos/:id' => 'carts#show_details_report'
get '/reportes/clientes' => 'clients#reports'
get '/reportes/productos' => 'product_variants#reports'
get '/reportes/ordenes_comparativa' => 'orders#reports'
get '/reportes/ordenes' => 'orders#reports_list'
get '/reportes/ordenes/:id' => 'orders#show_order'
get '/bancos' => 'banks#list'
get '/usuario/:id' => 'users#showuser'
get '/sucursales' => 'offices#list'
get '/messages' => 'dashboard#messages'
post '/post_message' => 'dashboard#post_message'
get '/providers_list' => 'site#providers_list'
get '/admin_product_search' => 'products#search'
get '/industrias' => 'industries#list'
get '/stocks/new/:id_product/:id_variant' => 'stocks#new'
get '/stocks/:id/edit/:id_product/:id_variant' => 'stocks#edit'

#Method for deserializable not found or not working
get '/product-variants' => 'product_variants#index'
get '/product-variants/:id' => 'product_variants#show'
post '/users' => 'users#create'
get '/ordenes/:id/edit' => 'orders#edit'
patch '/ordenes/:id' => 'orders#update'
get '/users' => 'users#index'
get '/users/:id' => 'users#show'
get '/usuarios/:id/contacto' => 'users#contact'
post '/users/do_contact' => 'users#do_contact'
get '/training' => 'trainings#training'
get '/carousel_list' => 'carousels#carousel_list'

#Site Routes
get '/category_products/:id' => 'site#category_products'
get '/subcategory_products/:id' => 'site#subcategory_products'
get '/manufacturer_products/:id' => 'site#manufacturer_products'
get '/product_details/:id' => 'site#product_details'
get '/dashboard' => 'dashboard#index'
get '/about_us' => 'site#about_us'
get '/product_categories' => 'site#product_categories'
get '/product_subcategories' => 'site#product_subcategories'
get '/product_offers' => 'site#product_offers'
get '/servicios' => 'site#servicios'
get '/contact' => 'site#contact'
get '/offices_list' => 'site#offices_list'
get '/training_list' => 'site#training_list'
get '/cart/:id' => 'carts#carrito'
post '/cart/do_quantity' => 'carts#do_quantity'
get '/orders/new/:id' => 'orders#new'
get '/confirm/:id' => 'orders#confirm'
post '/order/do_file' => 'orders#do_file'
get '/history/:id' => 'orders#history'
get '/users/:id/edit' => 'users#edit'
post '/users/do_edit' => 'users#do_edit'
post '/search' => 'site#search'



get '/new_test/:id' => 'carts#new_test'


end

app/models/training.rb
class Training < ApplicationRecord
    has_attached_file :docu
    validates_attachment_content_type :docu, content_type: "application/pdf"
    belongs_to :training_category
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_admin!
  layout "dashboard"
  # GET /trainings
  def index
    @trainings = Training.all
    render json: @trainings
  end

  def training
    @trainings = Training.all
  end

  # GET /trainings/1
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  def create
    @training = Training.new(training_params)

    if @training.save
      redirect_to '/training', notice: 'Documento creado correctamente'
    else
      render :new
    end
  end

  # PATCH/PUT /trainings/1
  def update
    if @training.update(training_params)
      redirect_to '/training', notice: 'Documento actualizado correctamente'
    else
      render :edit
    end
  end

  # DELETE /trainings/1
  def destroy
    @training.destroy
    redirect_to '/training', notice: 'Documento eliminado correctamente'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def training_params
      params.require(:training).permit(:name, :docu, :description, :videolink, :training_category_id)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_with(model: training, local: true, html: { multipart: true }) do |form| %>
  <% if training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Nombre" %>
    <%= form.text_field :name, id: :training_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Descripción" %>
    <%= form.text_field :description, id: :training_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Enlace a YouTube" %>
    <%= form.text_field :videolink, id: :training_videolink, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Documento de capacitacion" %>
    <%= form.file_field :docu, id: :product_docu_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Categoría" %>
    <%= form.collection_select :training_category_id, TrainingCategory.all, :id, :name, id: :training_training_category_id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Aceptar", class: "btn btn-success" %>
    <%= link_to "Atrás", "/training", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editar documento de capacitación</h1>

<%= render 'form', training: @training %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainings</h1>

<table class="table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.name %></td>
        <td><%= link_to 'Show', training %></td>
        <td><%= link_to 'Edit', edit_training_path(training) %></td>
        <td><%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training', new_training_path %>

app/views/trainings/new.html.erb
<h1>Nuevo documento de capacitación</h1>

<%= render 'form', training: @training %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @training.name %>
</p>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/training.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainings</h1>

<%= link_to 'Crear documento de capacitacion', new_training_path, class: "btn btn-primary" %>

<table class="table-responsive">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
     
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.name %></td>
        <td><%= training.description %></td>
        
        <td><iframe width="420" height="315" src="<%= training.videolink %>"></iframe></td>
        <td><%= link_to 'Editar', edit_training_path(training) %></td>
        <td><%= link_to 'Eliminar', training, method: :delete, data: { confirm: 'Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>