config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :abouts
  resources :industries
  resources :training_categories
  resources :carousels
  resources :trainings
  resources :offices
  resources :sold_products
  resources :banks
  resources :deliveries
  resources :destinations
  resources :stocks
  resources :extras
  resources :clients
  resources :contacts
  devise_for :users


  root 'site#index'

  resources :products
  resources :product_variants
  resources :manufacturers
  resources :providers
  resources :subcategories
  resources :categories
  resources :measures
  resources :orders
  resources :carts
  resources :password_resets
  resources :users

get 'password_resets/new'
post '/total' => 'orders#calculateTotal'
get '/pay/:id' => 'orders#pay'

#Admin Routes
get '/productos' => 'products#list'
get '/productos/:product_id/variantes' => 'product_variants#list'
get '/productos/:product_id/product_variants/new' => 'product_variants#new'
get '/productos/:product_id/product_variants/:id/edit' => 'product_variants#edit'
get '/unidades' => 'measures#list'
get '/fabricantes' =>'manufacturers#list'
get '/proveedores' =>'providers#list'
get '/categorias' => 'categories#list'
get '/subcategorias' => 'subcategories#list'
get '/contacto' => 'contacts#list'
get '/extra' => 'extras#list'
get '/almacen' => 'stocks#list'
get '/usuarios' => 'users#list'
get '/usuarios/:id/habilitar' => 'users#enable'
post '/users/do_enable' => 'users#do_enable'
delete '/usuarios/:id' => 'users#destroy'
get '/usuarios/:id/bloquear' => 'users#bloq'
get '/usuarios/:id/desbloquear' => 'users#desbloq'
get '/transportes' => 'transports#list'
get '/destinos' => 'destinations#list'
get '/envios' => 'deliveries#list'
get '/ordenes' => 'orders#list'
get '/ordenes/:id/editar' => 'orders#change'
post '/orders/do_change' => 'orders#do_change'
get '/reportes/productos_vendidos' => 'carts#reports'
get '/reportes/productos_stock' => 'stocks#reports'
get '/reportes/productos_vendidos/:id' => 'carts#show_details_report'
get '/reportes/clientes' => 'clients#reports'
get '/reportes/productos' => 'product_variants#reports'
get '/reportes/ordenes_comparativa' => 'orders#reports'
get '/reportes/ordenes' => 'orders#reports_list'
get '/reportes/ordenes/:id' => 'orders#show_order'
get '/bancos' => 'banks#list'
get '/usuario/:id' => 'users#showuser'
get '/sucursales' => 'offices#list'
get '/messages' => 'dashboard#messages'
post '/post_message' => 'dashboard#post_message'
get '/providers_list' => 'site#providers_list'
get '/admin_product_search' => 'products#search'
get '/industrias' => 'industries#list'
get '/stocks/new/:id_product/:id_variant' => 'stocks#new'
get '/stocks/:id/edit/:id_product/:id_variant' => 'stocks#edit'

#Method for deserializable not found or not working
get '/product-variants' => 'product_variants#index'
get '/product-variants/:id' => 'product_variants#show'
post '/users' => 'users#create'
get '/ordenes/:id/edit' => 'orders#edit'
patch '/ordenes/:id' => 'orders#update'
get '/users' => 'users#index'
get '/users/:id' => 'users#show'
get '/usuarios/:id/contacto' => 'users#contact'
post '/users/do_contact' => 'users#do_contact'
get '/training' => 'trainings#training'
get '/carousel_list' => 'carousels#carousel_list'

#Site Routes
get '/category_products/:id' => 'site#category_products'
get '/subcategory_products/:id' => 'site#subcategory_products'
get '/manufacturer_products/:id' => 'site#manufacturer_products'
get '/product_details/:id' => 'site#product_details'
get '/dashboard' => 'dashboard#index'
get '/about_us' => 'site#about_us'
get '/product_categories' => 'site#product_categories'
get '/product_subcategories' => 'site#product_subcategories'
get '/product_offers' => 'site#product_offers'
get '/servicios' => 'site#servicios'
get '/contact' => 'site#contact'
get '/offices_list' => 'site#offices_list'
get '/training_list' => 'site#training_list'
get '/cart/:id' => 'carts#carrito'
post '/cart/do_quantity' => 'carts#do_quantity'
get '/orders/new/:id' => 'orders#new'
get '/confirm/:id' => 'orders#confirm'
post '/order/do_file' => 'orders#do_file'
get '/history/:id' => 'orders#history'
get '/users/:id/edit' => 'users#edit'
post '/users/do_edit' => 'users#do_edit'
post '/search' => 'site#search'



get '/new_test/:id' => 'carts#new_test'


end

app/models/office.rb
class Office < ApplicationRecord
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  def name_with_city
    "#{name} - #{city}"
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_admin!
  layout "dashboard"
  # GET /offices
  def index
    @offices = Office.all
    render json: @offices
  end

  # GET /offices/1
  def show
    render json: @office
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  def create
    @office = Office.new(office_params)

    if @office.save
      redirect_to '/sucursales', notice: 'Office was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /offices/1
  def update
    if @office.update(office_params)
      redirect_to '/sucursales', notice: 'Office was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /offices/1
  def destroy
    @office.destroy
    redirect_to '/sucursales', notice: 'Office was successfully destroyed.'
  end

  #Metodos para admin
  def list
    @offices = Office.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def office_params
      params.require(:office).permit(:name, :city, :phone, :cellphone, :cellwsp, :address, :lat, :long, :email, :picture)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_with(model: office, local: true, html: { multipart: true }) do |form| %>
  <div class="form-group">
    <%= form.label "Nombre de sucursal" %>
    <%= form.text_field :name, id: :office_name, class: "form-control", :required => true, :maxlength => 100 %>
  </div>

  <div class="form-group">
    <%= form.label "Ciudad o Departamento" %>
    <%= form.text_field :city, id: :office_city, class: "form-control", :required => true, :maxlength => 100 %>
  </div>

  <div class="form-group">
    <%= form.label "Teléfono" %>
    <%= form.number_field :phone, id: :office_phone, class: "form-control", :required => true, :maxlength => 50 %>
  </div>

  <div class="form-group">
    <%= form.label "Celular" %>
    <%= form.number_field :cellphone, id: :office_cellphone, class: "form-control", :required => true, :maxlength => 50 %>
  </div>

  <div class="form-group">
    <%= form.label "Celular WhatsApp" %>
    <%= form.number_field :cellwsp, id: :office_cellwsp, class: "form-control", :required => true, :maxlength => 50 %>
  </div>

  <div class="form-group">
    <%= form.label "Dirección" %>
    <%= form.text_field :address, id: :office_address, class: "form-control", :required => true, :maxlength => 256 %>
  </div>

  <div class="form-group">
    <%= form.label "Latitud" %>
    <%= form.text_field :lat, id: :office_lat, class: "form-control", :required => true, :maxlength => 100 %>
  </div>

  <div class="form-group">
    <%= form.label "Longitud" %>
    <%= form.text_field :long, id: :office_long, class: "form-control", :required => true, :maxlength => 100 %>
  </div>

  <div class="form-group">
    <%= form.label "Correo eléctronico" %>
    <%= form.text_field :email, id: :office_email, class: "form-control", :required => true, :maxlength => 100 %>
  </div>

  <div class="form-group">
    <%= form.label "Imagen" %>
    <%= form.file_field :picture, id: :office_picture_id, class: "form-control" %>
  </div>

  <%if office.picture.url  != "/images/original/missing.png" %>
    <div class="form-group">
      <center><%= image_tag office.picture, class: "img-thumbnail" %></center>
    </div>
  <%end%>

  <div class="actions">
    <center>
      <%= form.submit "Aceptar", class: "btn btn-success" %>
      <%= link_to "Cancelar", "/sucursales", class: "btn btn-danger" %>
    </center>
  </div>
<% end %>

app/views/offices/edit.html.erb
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <h1>Editar surcursal</h1>
    <%= render 'form', office: @office %>
  </div>
</div>

app/views/offices/list.html.erb
<h1>Sucursales</h1>

<%= link_to 'Crear sucursal', new_office_path, class: "btn btn-primary"  %>
<div class="table-responsive">
  <table class="table table-stripped table-hover">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Ciudad o Departamento</th>
        <th>Teléfono</th>
        <th>Dirección</th>
        <th>Latitud</th>
        <th>Longitud</th>
        <th>Correo eléctronico</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @offices.each do |office| %>
        <tr>
          <td><%= office.name %></td>
          <td><%= office.city %></td>
          <td><%= office.phone %></td>
          <td><%= office.address %></td>
          <td><%= office.lat %></td>
          <td><%= office.long %></td>
          <td><%= office.email %></td>
          <td><%= link_to 'Editar', edit_office_path(office) %></td>
          <td><%= link_to 'Eliminar', office, method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/offices/new.html.erb
<div class="row">
    <div class="col-lg-10 offset-lg-1">
      <h1>Nueva sucursal</h1>
      <%= render 'form', office: @office %>
    </div>
</div>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @office.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @office.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @office.phone %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @office.cellphone %>
</p>

<p>
  <strong>Cellwsp:</strong>
  <%= @office.cellwsp %>
</p>

<p>
  <strong>Address:</strong>
  <%= @office.address %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @office.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @office.long %>
</p>

<p>
  <strong>Email:</strong>
  <%= @office.email %>
</p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>