config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :abouts
  resources :industries
  resources :training_categories
  resources :carousels
  resources :trainings
  resources :offices
  resources :sold_products
  resources :banks
  resources :deliveries
  resources :destinations
  resources :stocks
  resources :extras
  resources :clients
  resources :contacts
  devise_for :users


  root 'site#index'

  resources :products
  resources :product_variants
  resources :manufacturers
  resources :providers
  resources :subcategories
  resources :categories
  resources :measures
  resources :orders
  resources :carts
  resources :password_resets
  resources :users

get 'password_resets/new'
post '/total' => 'orders#calculateTotal'
get '/pay/:id' => 'orders#pay'

#Admin Routes
get '/productos' => 'products#list'
get '/productos/:product_id/variantes' => 'product_variants#list'
get '/productos/:product_id/product_variants/new' => 'product_variants#new'
get '/productos/:product_id/product_variants/:id/edit' => 'product_variants#edit'
get '/unidades' => 'measures#list'
get '/fabricantes' =>'manufacturers#list'
get '/proveedores' =>'providers#list'
get '/categorias' => 'categories#list'
get '/subcategorias' => 'subcategories#list'
get '/contacto' => 'contacts#list'
get '/extra' => 'extras#list'
get '/almacen' => 'stocks#list'
get '/usuarios' => 'users#list'
get '/usuarios/:id/habilitar' => 'users#enable'
post '/users/do_enable' => 'users#do_enable'
delete '/usuarios/:id' => 'users#destroy'
get '/usuarios/:id/bloquear' => 'users#bloq'
get '/usuarios/:id/desbloquear' => 'users#desbloq'
get '/transportes' => 'transports#list'
get '/destinos' => 'destinations#list'
get '/envios' => 'deliveries#list'
get '/ordenes' => 'orders#list'
get '/ordenes/:id/editar' => 'orders#change'
post '/orders/do_change' => 'orders#do_change'
get '/reportes/productos_vendidos' => 'carts#reports'
get '/reportes/productos_stock' => 'stocks#reports'
get '/reportes/productos_vendidos/:id' => 'carts#show_details_report'
get '/reportes/clientes' => 'clients#reports'
get '/reportes/productos' => 'product_variants#reports'
get '/reportes/ordenes_comparativa' => 'orders#reports'
get '/reportes/ordenes' => 'orders#reports_list'
get '/reportes/ordenes/:id' => 'orders#show_order'
get '/bancos' => 'banks#list'
get '/usuario/:id' => 'users#showuser'
get '/sucursales' => 'offices#list'
get '/messages' => 'dashboard#messages'
post '/post_message' => 'dashboard#post_message'
get '/providers_list' => 'site#providers_list'
get '/admin_product_search' => 'products#search'
get '/industrias' => 'industries#list'
get '/stocks/new/:id_product/:id_variant' => 'stocks#new'
get '/stocks/:id/edit/:id_product/:id_variant' => 'stocks#edit'

#Method for deserializable not found or not working
get '/product-variants' => 'product_variants#index'
get '/product-variants/:id' => 'product_variants#show'
post '/users' => 'users#create'
get '/ordenes/:id/edit' => 'orders#edit'
patch '/ordenes/:id' => 'orders#update'
get '/users' => 'users#index'
get '/users/:id' => 'users#show'
get '/usuarios/:id/contacto' => 'users#contact'
post '/users/do_contact' => 'users#do_contact'
get '/training' => 'trainings#training'
get '/carousel_list' => 'carousels#carousel_list'

#Site Routes
get '/category_products/:id' => 'site#category_products'
get '/subcategory_products/:id' => 'site#subcategory_products'
get '/manufacturer_products/:id' => 'site#manufacturer_products'
get '/product_details/:id' => 'site#product_details'
get '/dashboard' => 'dashboard#index'
get '/about_us' => 'site#about_us'
get '/product_categories' => 'site#product_categories'
get '/product_subcategories' => 'site#product_subcategories'
get '/product_offers' => 'site#product_offers'
get '/servicios' => 'site#servicios'
get '/contact' => 'site#contact'
get '/offices_list' => 'site#offices_list'
get '/training_list' => 'site#training_list'
get '/cart/:id' => 'carts#carrito'
post '/cart/do_quantity' => 'carts#do_quantity'
get '/orders/new/:id' => 'orders#new'
get '/confirm/:id' => 'orders#confirm'
post '/order/do_file' => 'orders#do_file'
get '/history/:id' => 'orders#history'
get '/users/:id/edit' => 'users#edit'
post '/users/do_edit' => 'users#do_edit'
post '/search' => 'site#search'



get '/new_test/:id' => 'carts#new_test'


end

app/models/industry.rb
class Industry < ApplicationRecord
    has_many :products
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :set_industry, only: [:show, :edit, :update, :destroy]
  ##before_action :authenticate_admin!
  layout "dashboard"
  # GET /industries
  def index
    @industries = Industry.all
    render json: @industries
  end

  # GET /industries/1
  def show
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries
  def create
    @industry = Industry.new(industry_params)

    if @industry.save
      redirect_to '/industrias', notice: 'Industry was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /industries/1
  def update
    if @industry.update(industry_params)
      redirect_to '/industrias', notice: 'Industry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /industries/1
  def destroy
    @industry.destroy
    redirect_to industries_url, notice: 'Industry was successfully destroyed.'
  end

  #Metodos admin
  def list
    @industries = Industry.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def industry_params
      params.require(:industry).permit(:country, :origin)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= form_with(model: industry, local: true) do |form| %>
  <div class="form-group">
    <%= form.label "País" %>
    <%= form.text_field :country, id: :industry_country, class: "form-control",  :required => true %>
  </div>

 <div class="form-group">
    <%= form.label "Origen" %>
    <%= form.text_field :origin, id: :industry_origin,  class: "form-control",  :required => true %>
  </div>

  <div class="actions">
   <center>
      <%= form.submit "Aceptar", class: "btn btn-success" %>
      <%= link_to "Cancelar", "/industrias", class: "btn btn-danger" %>
    </center>
  </div>
<% end %>

app/views/industries/edit.html.erb
<div class="row">
    <div class="col-lg-10 offset-lg-1">
        <h2>Editar industria</h2>
        <%= render 'form', industry: @industry %>
    </div>
</div>

app/views/industries/list.html.erb
<h1>Industrias</h1>
<%= link_to 'Crear industria', new_industry_path, class: "btn btn-primary" %>
<div class="table-responsive">
  <table class="table table-stripped table-hover">
    <thead>
      <tr>
        <th>País</th>
        <th>Origen</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @industries.each do |industry| %>
        <tr>
          <td><%= industry.country %></td>
          <td><%= industry.origin %></td>
          <td><%= link_to 'Editar', edit_industry_path(industry) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/industries/new.html.erb
<div class="row">
    <div class="col-lg-10 offset-lg-1">
        <h2>Crear industria</h2>
        <%= render 'form', industry: @industry %>
    </div>
</div>

app/views/industries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @industry.country %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @industry.origin %>
</p>

<%= link_to 'Edit', edit_industry_path(@industry) %> |
<%= link_to 'Back', industries_path %>